### ISSUE TITLE
Error message when installing the module....

### ISSUE THREAD

**Issue by libinruan** [qiliux/hexo-jupyter-notebook#7]
Hello, 

I tried to install your module on my Windows machine through Git Bash command line interface. I encountered the following error messages. I have installed pandoc (I used its msi) and nbconvert (via conda install).

Can anyone help me resolve the issue? Thanks.

Error message no. 1 occurred during the installation:

> $ npm i hexo-jupyter-notebook --save
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> \+ hexo-jupyter-notebook@0.0.3
> updated 1 package and audited 5876 packages in 6.672s
> found 1 low severity vulnerability
>   run `npm audit fix` to fix them, or `npm audit` for details

Error message no. 2 occurred when activating local Hexo server:

> ERROR Plugin load failed: hexo-jupyter-notebook
> Error: Cannot find module 'co'
>     at Function.Module._resolveFilename (module.js:536:15)
>     at Function.Module._load (module.js:466:25)
>     at Module.require (module.js:579:17)
>     at require (E:\GoogleDrive\GitHub\technical_note\node_modules\hexo\lib\hexo\index.js:227:21)
>     at E:\GoogleDrive\GitHub\technical_note\node_modules\hexo-jupyter-notebook\index.js:4:12
>     at fs.readFile.then.script (E:\GoogleDrive\GitHub\technical_note\node_modules\hexo\lib\hexo\index.js:240:12)
>     at tryCatcher (E:\GoogleDrive\GitHub\technical_note\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (E:\GoogleDrive\GitHub\technical_note\node_modules\bluebird\js\release\promise.js:512:31)
>     at Promise._settlePromise (E:\GoogleDrive\GitHub\technical_note\node_modules\bluebird\js\release\promise.js:569:18)
>     at Promise._settlePromise0 (E:\GoogleDrive\GitHub\technical_note\node_modules\bluebird\js\release\promise.js:614:10)
>     at Promise._settlePromises (E:\GoogleDrive\GitHub\technical_note\node_modules\bluebird\js\release\promise.js:694:18)
>     at Promise._fulfill (E:\GoogleDrive\GitHub\technical_note\node_modules\bluebird\js\release\promise.js:638:18)
>     at Promise._resolveCallback (E:\GoogleDrive\GitHub\technical_note\node_modules\bluebird\js\release\promise.js:432:57)
>     at Promise._settlePromiseFromHandler (E:\GoogleDrive\GitHub\technical_note\node_modules\bluebird\js\release\promise.js:524:17)
>     at Promise._settlePromise (E:\GoogleDrive\GitHub\technical_note\node_modules\bluebird\js\release\promise.js:569:18)
>     at Promise._settlePromise0 (E:\GoogleDrive\GitHub\technical_note\node_modules\bluebird\js\release\promise.js:614:10)
>     at Promise._settlePromises (E:\GoogleDrive\GitHub\technical_note\node_modules\bluebird\js\release\promise.js:694:18)
>     at Promise._fulfill (E:\GoogleDrive\GitHub\technical_note\node_modules\bluebird\js\release\promise.js:638:18)
>     at E:\GoogleDrive\GitHub\technical_note\node_modules\bluebird\js\release\nodeback.js:42:21
>     at E:\GoogleDrive\GitHub\technical_note\node_modules\graceful-fs\graceful-fs.js:78:16
>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by libinruan** [comment]
It seems that the issue is simply caused by the dependency of module co. After installing with the command `npm install co`, the issue is resolved.
